import json

from agents.input_agent import InputAgent
from agents.research_agent import ResearchAgent


# ============================================================
# TEST USER PROMPT
# ============================================================

USER_PROMPT = """
I want to design a gender-neutral fall jacket.

I want it to have an oversized silhouette with a
modern minimalist utility style.

The main colours should be dark green and cream.
I want large functional pockets and a simple construction
that a beginner could realistically make.

I don't want any visible logos, military styling, or
overly complicated construction.

The jacket should be practical for everyday use but still
look fashionable and clean.
"""


# ============================================================
# DISPLAY HELPER
# ============================================================

def print_section(title):
    print("\n")
    print("=" * 70)
    print(title)
    print("=" * 70)


def print_json(data):
    print(json.dumps(data, indent=4, ensure_ascii=False))


# ============================================================
# MAIN TEST
# ============================================================

def main():

    print_section("DESIGNLENS - AI PIPELINE TEST")

    # --------------------------------------------------------
    # 1. Display user prompt
    # --------------------------------------------------------

    print("\nUSER PROMPT:")
    print("-" * 70)
    print(USER_PROMPT.strip())

    # --------------------------------------------------------
    # 2. Initialize agents
    # --------------------------------------------------------

    print_section("INITIALIZING AI AGENTS")

    try:

        input_agent = InputAgent()
        research_agent = ResearchAgent()

        print("✓ Input Agent initialized")
        print("✓ Research Agent initialized")

    except Exception as e:

        print("\n✗ Failed to initialize agents")
        print(f"Error: {e}")

        return

    # --------------------------------------------------------
    # 3. INPUT AGENT
    # --------------------------------------------------------

    print_section("STEP 1 - INPUT AGENT / GROQ")

    print("Sending user prompt to Groq...")
    print("Please wait...")

    try:

        design_requirements = input_agent.analyze_input(
            USER_PROMPT
        )

    except Exception as e:

        print("\n✗ Input Agent failed")
        print(f"Error: {e}")

        return

    print("\n✓ Input Agent completed successfully")

    print("\nSTRUCTURED DESIGN REQUIREMENTS:")
    print("-" * 70)

    print_json(design_requirements)

    # --------------------------------------------------------
    # 4. RESEARCH AGENT
    # --------------------------------------------------------

    print_section("STEP 2 - RESEARCH AGENT / OLLAMA")

    print("Passing Input Agent output to Research Agent...")
    print("Please wait...")
    print("\nIMPORTANT:")
    print("The Research Agent is receiving the structured")
    print("requirements generated by the Input Agent.")
    print("It is NOT receiving the original prompt directly.")

    try:

        research_plan = research_agent.research_design(
            design_requirements
        )

    except Exception as e:

        print("\n✗ Research Agent failed")
        print(f"Error: {e}")

        return

    print("\n✓ Research Agent completed successfully")

    print("\nRESEARCH PLAN:")
    print("-" * 70)

    print_json(research_plan)

    # --------------------------------------------------------
    # 5. SUMMARY
    # --------------------------------------------------------

    print_section("AI PIPELINE SUMMARY")

    print("USER")
    print("  ↓")
    print("InputAgent / Groq")
    print("  ↓")
    print("DesignRequirements JSON")
    print("  ↓")
    print("ResearchAgent / Ollama 120B")
    print("  ↓")
    print("ResearchPlan JSON")

    # --------------------------------------------------------
    # 6. Quick verification
    # --------------------------------------------------------

    print_section("PIPELINE VERIFICATION")

    print("Input Agent output:")

    if isinstance(design_requirements, dict):
        print("  ✓ Valid Python dictionary")
    else:
        print("  ✗ Invalid output type")

    print("\nResearch Agent output:")

    if isinstance(research_plan, dict):
        print("  ✓ Valid Python dictionary")
    else:
        print("  ✗ Invalid output type")

    print("\nRequired Research Agent fields:")

    expected_fields = [
        "research_objective",
        "primary_search_queries",
        "alternative_search_queries",
        "visual_attributes",
        "ranking_priorities",
        "hard_requirements",
        "hard_exclusions",
        "soft_preferences",
        "diversity_categories"
    ]

    for field in expected_fields:

        if field in research_plan:
            print(f"  ✓ {field}")
        else:
            print(f"  ✗ {field}")

    # --------------------------------------------------------
    # 7. Final result
    # --------------------------------------------------------

    print_section("TEST COMPLETE")

    print(
        "✓ User prompt successfully interpreted by Groq"
    )

    print(
        "✓ Structured requirements successfully created"
    )

    print(
        "✓ Requirements successfully passed to Ollama"
    )

    print(
        "✓ Research plan successfully generated"
    )

    print(
        "\nThe two-agent AI pipeline is working."
    )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()