import os
import requests
from dotenv import load_dotenv

from filter_service import FilterService


load_dotenv()


class PexelsService:
    """
    Pexels Service for DesignForge.

    Responsibilities:
    - Communicate with the Pexels API.
    - Search for images using ResearchAgent queries.
    - Standardize Pexels responses.
    - Remove duplicate images.
    - Pass retrieved images to FilterService.

    This service does NOT:
    - Use AI.
    - Generate search queries.
    - Create the ResearchPlan.
    - Rank images.
    - Analyze image pixels.
    - Access the database.
    """

    BASE_URL = "https://api.pexels.com/v1/search"

    # ---------------------------------------------------------
    # INITIALIZATION
    # ---------------------------------------------------------

    def __init__(self):
        """
        Initialize the Pexels Service and Filter Service.
        """

        load_dotenv()

        self.api_key = os.getenv(
            "PEXELS_API_KEY"
        )

        if not self.api_key:
            raise ValueError(
                "PEXELS_API_KEY not found. "
                "Make sure your .env file contains: "
                "PEXELS_API_KEY=your_key"
            )

        # Pexels API authentication
        self.headers = {
            "Authorization": self.api_key
        }

        # Filter Service
        self.filter_service = FilterService()

    # ---------------------------------------------------------
    # SEARCH ONE QUERY
    # ---------------------------------------------------------

    def search_images(
        self,
        query,
        per_page=5
    ):
        """
        Search Pexels using one query.

        Args:
            query:
                Search query generated by ResearchAgent.

            per_page:
                Number of results requested from Pexels.

        Returns:
            List of standardized image dictionaries.
        """

        if not query or not isinstance(
            query,
            str
        ):
            return []

        params = {
            "query": query,
            "per_page": per_page
        }

        try:

            response = requests.get(
                self.BASE_URL,
                headers=self.headers,
                params=params,
                timeout=10
            )

            response.raise_for_status()

            data = response.json()

            return self._format_results(
                data.get("photos", []),
                query
            )

        except requests.exceptions.RequestException as e:

            print(
                f"Pexels API error for "
                f"'{query}': {e}"
            )

            return []

    # ---------------------------------------------------------
    # SEARCH RESEARCH PLAN
    # ---------------------------------------------------------

    def search_research_plan(
        self,
        research_plan,
        primary_per_query=4,
        alternative_per_query=2,
        max_results=20
    ):
        """
        Search Pexels using the ResearchAgent's ResearchPlan.

        This method:

            ResearchPlan
                ↓
            Pexels searches
                ↓
            Raw image references
                ↓
            Duplicate removal
                ↓
            FilterService
                ↓
            Final filtered references

        Args:
            research_plan:
                ResearchPlan generated by ResearchAgent.

            primary_per_query:
                Results requested for each primary query.

            alternative_per_query:
                Results requested for each alternative query.

            max_results:
                Maximum number of raw images collected
                before filtering.

        Returns:
            {
                "raw_results": {...},
                "filtered_results": {...}
            }
        """

        if not isinstance(
            research_plan,
            dict
        ):
            raise TypeError(
                "research_plan must be a dictionary"
            )

        # -----------------------------------------------------
        # GET SEARCH QUERIES
        # -----------------------------------------------------

        primary_queries = research_plan.get(
            "primary_search_queries",
            []
        )

        alternative_queries = research_plan.get(
            "alternative_search_queries",
            []
        )

        if not isinstance(
            primary_queries,
            list
        ):
            primary_queries = []

        if not isinstance(
            alternative_queries,
            list
        ):
            alternative_queries = []

        # -----------------------------------------------------
        # STORAGE
        # -----------------------------------------------------

        results = []

        queries_used = []

        # -----------------------------------------------------
        # PRIMARY QUERIES
        # -----------------------------------------------------

        for query in primary_queries:

            if len(results) >= max_results:
                break

            images = self.search_images(
                query=query,
                per_page=primary_per_query
            )

            results.extend(images)

            if images:
                queries_used.append(query)

        # -----------------------------------------------------
        # ALTERNATIVE QUERIES
        # -----------------------------------------------------

        for query in alternative_queries:

            if len(results) >= max_results:
                break

            images = self.search_images(
                query=query,
                per_page=alternative_per_query
            )

            results.extend(images)

            if images:
                queries_used.append(query)

        # -----------------------------------------------------
        # REMOVE DUPLICATES
        # -----------------------------------------------------

        results = self._remove_duplicates(
            results
        )

        # Limit raw results
        results = results[:max_results]

        # -----------------------------------------------------
        # RAW RESULTS
        # -----------------------------------------------------

        raw_results = {
            "images": results,

            "queries_used": queries_used,

            "total_results": len(results)
        }

        # -----------------------------------------------------
        # FILTER RESULTS
        # -----------------------------------------------------

        print(
            "\n[PexelsService] "
            "Sending results to FilterService..."
        )

        filtered_results = (
            self.filter_service.filter_images(
                raw_results,
                research_plan
            )
        )

        print(
            "[PexelsService] "
            f"Filtering complete. "
            f"{filtered_results['total_after_filtering']} "
            f"images remain."
        )

        # -----------------------------------------------------
        # RETURN BOTH
        # -----------------------------------------------------

        return {
            "raw_results": raw_results,

            "filtered_results": filtered_results
        }

    # ---------------------------------------------------------
    # FORMAT PEXELS RESULTS
    # ---------------------------------------------------------

    def _format_results(
        self,
        photos,
        query
    ):
        """
        Convert raw Pexels API responses into the
        standardized DesignForge image structure.
        """

        formatted = []

        for photo in photos:

            formatted.append({

                "id": photo.get(
                    "id"
                ),

                "source": "pexels",

                "query": query,

                "image_url": (
                    photo.get(
                        "src",
                        {}
                    ).get(
                        "large"
                    )
                ),

                "original_url": (
                    photo.get(
                        "src",
                        {}
                    ).get(
                        "original"
                    )
                ),

                "thumbnail_url": (
                    photo.get(
                        "src",
                        {}
                    ).get(
                        "medium"
                    )
                ),

                "width": photo.get(
                    "width"
                ),

                "height": photo.get(
                    "height"
                ),

                "photographer": photo.get(
                    "photographer"
                ),

                "photographer_url": photo.get(
                    "photographer_url"
                ),

                "pexels_url": photo.get(
                    "url"
                )
            })

        return formatted

    # ---------------------------------------------------------
    # REMOVE DUPLICATES
    # ---------------------------------------------------------

    def _remove_duplicates(
        self,
        images
    ):
        """
        Remove duplicate Pexels images using their ID.
        """

        unique_images = []

        seen_ids = set()

        for image in images:

            image_id = image.get(
                "id"
            )

            if image_id is None:
                continue

            if image_id not in seen_ids:

                seen_ids.add(
                    image_id
                )

                unique_images.append(
                    image
                )

        return unique_images